import { engine } from './engine.js';
import { logger, setLifecycle, registerModule, captureError, verifyButtons, runHealthChecks, diagnosticSnapshot, installGlobalHandlers } from './diagnostics.js';
installGlobalHandlers();
setLifecycle('loading-ui');
const app=document.querySelector('#app');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>new Intl.NumberFormat().format(n||0);
let view='chat', selectedDoc=null, busy=false, importQueue=[];

app.innerHTML=`
<div class="shell">
 <aside class="rail">
  <div class="brand"><div class="mark">M</div><div><strong>Mission Companion</strong><span>SME Workspace · Master 2.0</span></div></div>
  <nav>
   <button data-view="chat" class="active">Command Desk</button>
   <button data-view="knowledge">Knowledge Base</button>
   <button data-view="sources">Source Inspector</button>
   <button data-view="evaluate">SME Evaluations</button>
   <button data-view="settings">Settings</button>
   <button data-view="diagnostics">Diagnostics</button>
  </nav>
  <div class="project-block"><label>ACTIVE PROJECT</label><select id="projectSelect"></select><button id="newProject" class="subtle">＋ New project</button></div>
  <div class="rail-foot"><span class="dot" id="healthDot"></span><span id="healthText">Starting…</span></div>
 </aside>
 <main>
  <header class="topbar"><div><div class="eyebrow">MISSION COMPANION</div><h1 id="pageTitle">Command Desk</h1><p id="pageSub">Ask project-specific questions and receive source-grounded answers.</p></div><div class="mode-wrap"><label>ANSWER MODE</label><select id="mode"><option value="source">Source-only</option><option value="assisted">SME-assisted</option><option value="general">General assistant</option></select></div></header>
  <section id="chat" class="view active">
   <div class="kpis"><article><span>DOCUMENTS</span><strong id="kDocs">0</strong></article><article><span>INDEXED SECTIONS</span><strong id="kSections">0</strong></article><article><span>ANSWER STANDARD</span><strong id="kMode">Source-only</strong></article><article><span>AI</span><strong id="kAI">Not configured</strong></article></div>
   <div class="chat-layout">
    <section class="panel conversation"><div class="panel-head"><div><span>PROJECT ANALYSIS</span><h2>Ask Mission Companion</h2></div><button id="clearChat" class="subtle">New conversation</button></div><div id="messages" class="messages"></div><div class="composer"><textarea id="prompt" placeholder="Ask a question about the selected project knowledge…"></textarea><button id="send">Analyze</button></div><div class="hint">Enter sends · Shift+Enter adds a line</div></section>
    <aside class="panel evidence"><div class="panel-head"><div><span>RETRIEVAL</span><h2>Evidence used</h2></div></div><div id="evidenceList" class="evidence-list"><div class="empty">Sources used in the latest answer appear here.</div></div></aside>
   </div>
  </section>
  <section id="knowledge" class="view"><div class="knowledge-grid">
   <aside class="panel library-panel"><div class="panel-head"><div><span>KNOWLEDGE ORGANIZATION</span><h2>Libraries</h2></div><button id="newLibrary" class="subtle">＋ New</button></div><div id="libraries" class="library-list"></div></aside>
   <section class="panel knowledge-main"><div class="panel-head"><div><span>INGESTION PIPELINE</span><h2 id="activeLibraryTitle">Knowledge library</h2></div><div><input id="fileInput" type="file" multiple hidden accept=".pdf,.docx,.xlsx,.xls,.txt,.md,.csv,.json,.html,.xml,.log"><button id="upload">＋ Add documents</button></div></div><div class="pipeline"><span>Upload</span><b>→</b><span>Extract</span><b>→</b><span>Detect sections</span><b>→</b><span>Index</span><b>→</b><span>Verify</span></div><div id="ingestStatus"></div><div class="knowledge-toolbar"><input id="documentFilter" placeholder="Filter documents…"><select id="categoryFilter"><option value="">All categories</option><option>Specifications</option><option>Drawings</option><option>SOPs</option><option>Reports</option><option>Photos</option><option>General</option></select></div><div id="documents" class="document-list"></div></section>
   <aside class="panel metadata-panel"><div class="panel-head"><div><span>DOCUMENT CONTROL</span><h2>Metadata</h2></div></div><div id="documentMetadata" class="document-metadata"><div class="empty">Select a document to review its health and metadata.</div></div><div class="queue-head"><span>IMPORT ACTIVITY</span><strong>Queue</strong></div><div id="importQueue" class="import-queue"><div class="empty">No imports in this session.</div></div></aside>
  </div></section>
  <section id="sources" class="view"><div class="split source-split"><section class="panel"><div class="panel-head"><div><span>DOCUMENT STRUCTURE</span><h2>Source inspector</h2></div></div><div id="sourceDocs" class="source-docs"></div></section><section class="panel"><div id="sourceDetail" class="source-detail"><div class="empty">Choose a document to inspect its indexed sections.</div></div></section></div></section>
  <section id="evaluate" class="view"><div class="split"><section class="panel"><div class="panel-head"><div><span>ACCURACY BENCHMARK</span><h2>SME evaluation cases</h2></div><button id="addEval">＋ Add case</button></div><p class="intro">Create known-answer questions. Each run scores required facts, prohibited assumptions, source retrieval, and citation use.</p><div id="evalList"></div></section><aside class="panel"><h3>Evaluation standard</h3><p><strong>Required facts</strong> are phrases the answer must contain.</p><p><strong>Expected source</strong> is a document or section the retrieval should find.</p><p><strong>Prohibited assumptions</strong> are statements that must not appear.</p><div id="evalResult"></div></aside></div></section>
  <section id="settings" class="view"><section class="panel settings"><div class="panel-head"><div><span>APPLICATION SETTINGS</span><h2>Settings</h2></div></div><div class="settings-tabs"><button class="active" data-settings-tab="ai">AI</button><button data-settings-tab="knowledge">Knowledge</button><button data-settings-tab="developer">Developer</button><button data-settings-tab="about">About</button></div><div class="settings-pane active" data-settings-pane="ai"><label>OpenAI API URL<input id="apiUrl"></label><label>Model<input id="model"></label><label>API key<input id="apiKey" type="password" autocomplete="off"></label><label>Request timeout (seconds)<input id="timeout" type="number" min="30" max="600"></label><button id="testConnection" class="subtle">Test connection</button></div><div class="settings-pane" data-settings-pane="knowledge"><label>Retrieved sections per question<input id="topK" type="number" min="3" max="20"></label><div class="settings-actions"><button id="exportProject" class="subtle">Export project</button><label class="button subtle">Import project<input id="importProject" type="file" accept=".json" hidden></label></div></div><div class="settings-pane" data-settings-pane="developer"><p class="notice">Reset removes all projects, settings, indexed documents, and browser history for this application.</p><button id="openDiagnostics" class="subtle">Open diagnostics</button><button id="resetApplication" class="danger">Reset application data</button></div><div class="settings-pane" data-settings-pane="about"><h3>Mission Companion Master</h3><p>Version <strong>2.5.0 — Build 4</strong></p><p class="notice">Evidence-first SME workspace. Build 4 adds query expansion, exact-term and heading weighting, retrieval reranking, potential source-conflict detection, and answer-level citation verification.</p></div><div class="settings-actions"><button id="saveSettings">Save settings</button></div><p class="notice">The API key is stored only in this browser. A public static website cannot safely share one central key.</p></section></section>
  <section id="diagnostics" class="view"><div class="diagnostic-grid"><section class="panel"><div class="panel-head"><div><span>SYSTEM HEALTH</span><h2>Diagnostics</h2></div><div><button id="runDiagnostics">Run checks</button><button id="exportDiagnostics" class="subtle">Export</button></div></div><div id="healthSummary" class="health-summary"></div><div id="healthChecks" class="health-checks"></div></section><section class="panel"><div class="panel-head"><div><span>DEVELOPER CONSOLE</span><h2>Application log</h2></div><button id="clearLogs" class="subtle">Clear log</button></div><div id="diagnosticLog" class="diagnostic-log"></div></section><section class="panel roadmap-panel"><div class="panel-head"><div><span>MASTER ROADMAP</span><h2>Build sequence</h2></div></div><ol class="roadmap"><li class="done"><strong>Build 1</strong><span>Stabilization and diagnostics</span></li><li class="done"><strong>Build 2</strong><span>Libraries, ingestion management, metadata, and document health</span></li><li class="done"><strong>Build 3</strong><span>Source Inspector and extraction verification</span></li><li class="done"><strong>Build 4</strong><span>Retrieval and reranking</span></li><li><strong>Build 5</strong><span>Evidence-controlled answer engine</span></li><li><strong>Build 6</strong><span>Citation accuracy</span></li><li><strong>Build 7</strong><span>SME evaluation suite</span></li><li><strong>Build 8–10</strong><span>Knowledge packs, security, and production release</span></li></ol></section></div></section>
 </main>
</div>
<div id="modal" class="modal" hidden><div class="modal-card"><button id="closeModal" class="modal-x">×</button><div id="modalBody"></div></div></div>`;

const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const titles={diagnostics:['Diagnostics','Inspect application health, startup checks, logs, and roadmap.'],chat:['Command Desk','Ask project-specific questions and receive source-grounded answers.'],knowledge:['Knowledge Base','Build a structured, section-aware project library.'],sources:['Source Inspector','Review exactly what Mission Companion indexed.'],evaluate:['SME Evaluations','Measure accuracy against known questions and required evidence.'],settings:['Settings','Configure the model and move project libraries between browsers.']};
function show(name){view=name;$$('.view').forEach(x=>x.classList.toggle('active',x.id===name));$$('nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===name));$('#pageTitle').textContent=titles[name][0];$('#pageSub').textContent=titles[name][1];if(name==='knowledge')renderKnowledgeWorkspace();if(name==='sources')renderSources();if(name==='evaluate')renderEvals();if(name==='diagnostics')renderDiagnostics()}
$$('nav button').forEach(b=>{b.onclick=()=>show(b.dataset.view);b.dataset.bound='true'});registerModule('Navigation','ready',{summary:`${$$('nav button').length} views registered`});
function state(){return engine.state()}
function modeLabel(m){return {source:'Source-only',assisted:'SME-assisted',general:'General assistant'}[m]}
async function refresh(){const s=state();$('#mode').value=s.settings.mode;$('#kMode').textContent=modeLabel(s.settings.mode);$('#kAI').textContent=s.settings.openaiKey?'Configured':'Not configured';$('#projectSelect').innerHTML=s.projects.map(p=>`<option value="${p.id}" ${p.id===s.activeProject?'selected':''}>${esc(p.name)}</option>`).join('');const docs=await engine.documents(),sections=await engine.sections();$('#kDocs').textContent=fmt(docs.length);$('#kSections').textContent=fmt(sections.length);renderMessages();await renderKnowledgeWorkspace(docs)}
$('#mode').onchange=()=>{engine.saveSettings({mode:$('#mode').value});refresh()};
$('#projectSelect').onchange=async()=>{engine.setProject($('#projectSelect').value);selectedDoc=null;await refresh()};
$('#newProject').onclick=()=>openModal(`<h2>Create project</h2><label>Project name<input id="projectName" autofocus></label><button id="createProject">Create</button>`,()=>{$('#createProject').onclick=()=>{const n=$('#projectName').value.trim();if(n){engine.addProject(n);closeModal();refresh()}}});
function renderMessages(){const chat=state().chat;$('#messages').innerHTML=chat.length?chat.map(m=>`<article class="message ${m.role}"><div class="avatar">${m.role==='user'?'YOU':'MC'}</div><div><div class="message-meta">${m.role==='user'?'You':'Mission Companion'}${m.mode?` · ${modeLabel(m.mode)}`:''}</div><div class="message-text">${esc(m.content).replace(/\n/g,'<br>')}</div></div></article>`).join(''):`<div class="welcome"><div class="seal">M</div><h3>Build an evidence-backed SME</h3><p>Add project documents, choose Source-only mode, and ask questions. Mission Companion will retrieve the most relevant sections, cite them, and identify evidence gaps.</p></div>`;$('#messages').scrollTop=$('#messages').scrollHeight}
$('#clearChat').onclick=()=>{engine.clearChat();refresh()};
async function ask(){const prompt=$('#prompt').value.trim();if(!prompt||busy)return;busy=true;$('#send').disabled=true;$('#send').textContent='Analyzing…';try{const m=await engine.ask(prompt,$('#mode').value);$('#prompt').value='';renderMessages();renderEvidence(m.hits,m.citations,m.citationVerification,m.retrievalMeta)}catch(e){captureError(e,{module:'Conversation',action:'ask'});alert(e.message)}finally{busy=false;$('#send').disabled=false;$('#send').textContent='Analyze'}}
$('#send').onclick=ask;$('#prompt').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();ask()}};
function renderEvidence(hits=[],used=[],verification=null,meta={}){const summary=hits.length?`<div class="retrieval-summary"><span>${hits.length} sources</span><span>${meta?.totalCandidates||hits.length} candidates</span><span>citation coverage ${verification?.coverage??'—'}%</span><span class="${verification?.passed?'good-text':'warn-text'}">${verification?.passed?'citations verified':'review citations'}</span></div>${(meta?.conflicts||[]).length?`<div class="conflict-alert"><strong>Potential source conflict</strong>${meta.conflicts.map(c=>`<span>[S${c.sourceA}] ↔ [S${c.sourceB}] · ${esc(c.reason)}</span>`).join('')}</div>`:''}`:'';$('#evidenceList').innerHTML=summary+(hits.length?hits.map(h=>`<article class="evidence-item ${used.includes(h.sourceNumber)?'used':''}"><div><strong>[S${h.sourceNumber}] ${esc(h.heading)}</strong><span>${esc(h.documentName)} · ${esc(h.location)} · score ${h.score.toFixed(1)}</span></div><div class="match-tags">${(h.matchedTerms||[]).slice(0,6).map(t=>`<em>${esc(t)}</em>`).join('')}</div><p>${esc(h.text.slice(0,320))}${h.text.length>320?'…':''}</p></article>`).join(''):'<div class="empty">No project evidence was retrieved.</div>')}
$('#upload').onclick=()=>$('#fileInput').click();
$('#fileInput').onchange=async()=>{const files=[...$('#fileInput').files];if(!files.length)return;const libraryId=state().activeLibrary;importQueue=files.map((f,i)=>({id:`q-${Date.now()}-${i}`,name:f.name,status:'waiting',detail:'Waiting to process'}));renderImportQueue();$('#ingestStatus').innerHTML='<div class="progress">Preparing files…</div>';try{const r=await engine.ingest(files,p=>{importQueue=importQueue.map((q,i)=>i<p.current-1?{...q,status:'complete',detail:'Indexed'}:i===p.current-1?{...q,status:'processing',detail:'Extracting and indexing'}:q);renderImportQueue();$('#ingestStatus').innerHTML=`<div class="progress">Processing ${esc(p.name)} (${p.current}/${p.total})…</div>`},libraryId);importQueue=importQueue.map(q=>{const failed=r.documents.find(d=>d.name===q.name&&d.status==='error');const skipped=r.skipped?.find(d=>d.name===q.name);return failed?{...q,status:'error',detail:failed.error}:skipped?{...q,status:'skipped',detail:skipped.reason}:{...q,status:'complete',detail:'Indexed and verified'}});renderImportQueue();$('#ingestStatus').innerHTML=`<div class="success">Indexed ${r.sections.length} sections from ${r.documents.filter(d=>d.status==='verified').length} document(s).${r.skipped?.length?` Skipped ${r.skipped.length} duplicate(s).`:''}</div>`}catch(e){importQueue=importQueue.map(q=>q.status==='complete'?q:{...q,status:'error',detail:e.message});renderImportQueue();$('#ingestStatus').innerHTML=`<div class="error">${esc(e.message)}</div>`}finally{$('#fileInput').value='';await refresh()}};
$('#documentFilter').oninput=()=>renderKnowledgeWorkspace();$('#categoryFilter').onchange=()=>renderKnowledgeWorkspace();
$('#newLibrary').onclick=()=>openModal(`<h2>Create knowledge library</h2><label>Library name<input id="libraryName" autofocus></label><label>Description<textarea id="libraryDescription"></textarea></label><button id="createLibrary">Create library</button>`,()=>{$('#createLibrary').onclick=async()=>{const name=$('#libraryName').value.trim();if(!name)return;engine.addLibrary(name,$('#libraryDescription').value);closeModal();await refresh()}});
function renderImportQueue(){$('#importQueue').innerHTML=importQueue.length?importQueue.map(q=>`<article class="queue-item ${q.status}"><span class="queue-state">${q.status==='complete'?'✓':q.status==='error'?'×':q.status==='processing'?'↻':q.status==='skipped'?'—':'…'}</span><div><strong>${esc(q.name)}</strong><small>${esc(q.detail)}</small></div></article>`).join(''):'<div class="empty">No imports in this session.</div>'}
async function renderKnowledgeWorkspace(prefetched=null){const s=state(),libraries=engine.libraries(),allDocs=prefetched||await engine.documents();const active=libraries.find(l=>l.id===s.activeLibrary)||libraries[0];if(active&&active.id!==s.activeLibrary)engine.setLibrary(active.id);$('#libraries').innerHTML=libraries.length?libraries.map(l=>{const count=allDocs.filter(d=>d.libraryId===l.id).length;return `<article class="library-card ${l.id===active?.id?'active':''} ${l.enabled?'':'disabled'}" data-library="${l.id}"><button class="library-select" data-library-select="${l.id}"><strong>${esc(l.name)}</strong><span>${count} document${count===1?'':'s'} · ${l.enabled?'Enabled':'Disabled'}</span></button><div class="library-actions"><button class="subtle" data-library-edit="${l.id}">Edit</button><button class="subtle" data-library-toggle="${l.id}">${l.enabled?'Disable':'Enable'}</button><button class="danger" data-library-delete="${l.id}">×</button></div></article>`}).join(''):'<div class="empty">No libraries.</div>';$('#activeLibraryTitle').textContent=active?.name||'Knowledge library';let docs=active?allDocs.filter(d=>d.libraryId===active.id):[];const q=$('#documentFilter').value.trim().toLowerCase(),category=$('#categoryFilter').value;if(q)docs=docs.filter(d=>`${d.name} ${d.title||''} ${(d.tags||[]).join(' ')}`.toLowerCase().includes(q));if(category)docs=docs.filter(d=>d.category===category);renderDocuments(docs);renderImportQueue();$$('[data-library-select]').forEach(b=>b.onclick=async()=>{engine.setLibrary(b.dataset.librarySelect);selectedDoc=null;await refresh()});$$('[data-library-toggle]').forEach(b=>b.onclick=async()=>{const l=libraries.find(x=>x.id===b.dataset.libraryToggle);engine.updateLibrary(l.id,{enabled:!l.enabled});await refresh()});$$('[data-library-edit]').forEach(b=>b.onclick=()=>{const l=libraries.find(x=>x.id===b.dataset.libraryEdit);openModal(`<h2>Edit library</h2><label>Name<input id="editLibraryName" value="${esc(l.name)}"></label><label>Description<textarea id="editLibraryDescription">${esc(l.description||'')}</textarea></label><button id="saveLibrary">Save</button>`,()=>{$('#saveLibrary').onclick=async()=>{engine.updateLibrary(l.id,{name:$('#editLibraryName').value.trim()||l.name,description:$('#editLibraryDescription').value.trim()});closeModal();await refresh()}})});$$('[data-library-delete]').forEach(b=>b.onclick=async()=>{if(confirm('Delete this library and every document indexed inside it?')){try{await engine.deleteLibrary(b.dataset.libraryDelete);await refresh()}catch(e){alert(e.message)}}})}
function renderDocuments(docs){$('#documents').innerHTML=docs.length?docs.map(d=>`<article class="doc ${d.status} ${d.id===selectedDoc?'selected':''}" data-document-row="${d.id}"><div class="file-icon">${(d.extension||d.name.split('.').pop()||'DOC').toUpperCase().slice(0,4)}</div><div class="doc-main"><strong>${esc(d.title||d.name)}</strong><span>${esc(d.category||'General')} · ${fmt(d.sectionCount)} sections · ${formatBytes(d.size)}</span><small class="health ${esc(d.health||'warning')}">${esc(d.health||d.status)} — ${esc(d.healthDetail||d.error||'No health details')}</small></div><button class="subtle" data-inspect="${d.id}">Inspect</button><button class="danger" data-remove="${d.id}">Remove</button></article>`).join(''):'<div class="empty">No documents in this library match the current filter.</div>';$$('[data-document-row]').forEach(row=>row.onclick=e=>{if(e.target.closest('button'))return;selectedDoc=row.dataset.documentRow;renderDocumentMetadata(docs.find(d=>d.id===selectedDoc));renderDocuments(docs)});$$('[data-remove]').forEach(b=>b.onclick=async()=>{if(confirm('Remove this document and all indexed sections?')){await engine.removeDocument(b.dataset.remove);if(selectedDoc===b.dataset.remove)selectedDoc=null;refresh()}});$$('[data-inspect]').forEach(b=>b.onclick=()=>{selectedDoc=b.dataset.inspect;show('sources')});renderDocumentMetadata(docs.find(d=>d.id===selectedDoc))}
function renderDocumentMetadata(d){$('#documentMetadata').innerHTML=d?`<div class="metadata-health ${esc(d.health||'warning')}"><span>${d.health==='healthy'?'✓':d.health==='error'?'×':'!'}</span><div><strong>${esc((d.health||'warning').toUpperCase())}</strong><small>${esc(d.healthDetail||'No details')}</small></div></div><dl><dt>Title</dt><dd>${esc(d.title||d.name)}</dd><dt>Filename</dt><dd>${esc(d.name)}</dd><dt>Category</dt><dd>${esc(d.category||'General')}</dd><dt>Type</dt><dd>${esc(d.extension?.toUpperCase()||d.type||'Unknown')}</dd><dt>Size</dt><dd>${formatBytes(d.size)}</dd><dt>Sections</dt><dd>${fmt(d.sectionCount)}</dd><dt>Characters</dt><dd>${fmt(d.characterCount)}</dd><dt>Indexed</dt><dd>${new Date(d.indexedAt).toLocaleString()}</dd></dl>`:'<div class="empty">Select a document to review its health and metadata.</div>'}
function formatBytes(n=0){if(n<1024)return `${n} B`;if(n<1048576)return `${(n/1024).toFixed(1)} KB`;return `${(n/1048576).toFixed(1)} MB`}
async function renderSources(){
 const docs=await engine.documents(),sections=await engine.sections();
 $('#sourceDocs').innerHTML=`<div class="source-filter"><input id="sourceDocumentFilter" placeholder="Filter source documents…"></div><div id="sourceDocumentList"></div>`;
 const drawDocs=()=>{const q=($('#sourceDocumentFilter')?.value||'').trim().toLowerCase();const shown=docs.filter(d=>`${d.name} ${d.title||''} ${d.category||''}`.toLowerCase().includes(q));$('#sourceDocumentList').innerHTML=shown.length?shown.map(d=>`<button class="source-doc ${d.id===selectedDoc?'active':''}" data-doc="${d.id}"><span><strong>${esc(d.title||d.name)}</strong><small>${esc(d.category||'General')} · ${esc((d.health||'warning').toUpperCase())}</small></span><b>${fmt(d.sectionCount)}</b></button>`).join(''):'<div class="empty">No matching documents.</div>';$$('[data-doc]').forEach(b=>b.onclick=()=>{selectedDoc=b.dataset.doc;renderSources()})};
 $('#sourceDocumentFilter').oninput=drawDocs;drawDocs();
 const selected=docs.find(d=>d.id===selectedDoc)||docs[0];if(!selected){$('#sourceDetail').innerHTML='<div class="empty">No indexed documents.</div>';return}
 selectedDoc=selected.id;const ss=sections.filter(s=>s.documentId===selected.id).sort((a,b)=>a.order-b.order);
 const totalWords=ss.reduce((n,x)=>n+(x.wordCount||x.text?.trim().split(/\s+/).length||0),0);const empty=ss.filter(x=>!x.text?.trim()).length;const tiny=ss.filter(x=>(x.characters||0)<120).length;const duplicateHeadings=Object.entries(ss.reduce((m,x)=>(m[x.heading]=(m[x.heading]||0)+1,m),{})).filter(([,n])=>n>1).length;
 const report={document:selected.name,health:selected.health||'warning',sections:ss.length,characters:selected.characterCount||0,words:totalWords,emptySections:empty,shortSections:tiny,duplicateHeadings,generatedAt:new Date().toISOString()};
 $('#sourceDetail').innerHTML=`<div class="source-title"><span>EXTRACTION VERIFICATION</span><h2>${esc(selected.title||selected.name)}</h2><p>${esc(selected.name)} · ${esc(selected.category||'General')}</p></div><div class="inspection-kpis"><article><span>SECTIONS</span><strong>${fmt(ss.length)}</strong></article><article><span>WORDS</span><strong>${fmt(totalWords)}</strong></article><article><span>CHARACTERS</span><strong>${fmt(selected.characterCount)}</strong></article><article><span>HEALTH</span><strong class="health ${esc(selected.health||'warning')}">${esc((selected.health||'warning').toUpperCase())}</strong></article></div><div class="inspection-toolbar"><input id="sectionFilter" placeholder="Search headings or extracted text…"><select id="sectionLevel"><option value="">All levels</option>${[1,2,3,4,5,6].map(n=>`<option value="${n}">Level ${n}</option>`).join('')}</select><button id="expandSections" class="subtle">Expand all</button><button id="collapseSections" class="subtle">Collapse all</button><button id="exportExtraction" class="subtle">Export report</button></div><div class="extraction-report ${empty||tiny?'attention':'healthy'}"><strong>${empty?'Extraction needs attention':tiny?'Review short sections':'Extraction verified'}</strong><span>${empty} empty · ${tiny} short · ${duplicateHeadings} duplicate heading${duplicateHeadings===1?'':'s'}</span></div><div id="sectionResults"></div>`;
 const drawSections=()=>{const q=($('#sectionFilter').value||'').trim().toLowerCase(),level=$('#sectionLevel').value;const shown=ss.filter(x=>(!q||`${x.heading} ${x.text}`.toLowerCase().includes(q))&&(!level||String(x.level||1)===level));$('#sectionResults').innerHTML=shown.length?shown.map((x,i)=>`<details class="source-section" ${i===0&&!q?'open':''}><summary><b>${x.order+1}</b><span style="--level:${Math.max(0,(x.level||1)-1)}"><strong>${esc(x.heading)}</strong><small>${esc((x.path||[]).join(' › ')||x.location)} · ${fmt(x.characters)} chars · ${fmt(x.wordCount||0)} words</small></span><em>L${x.level||1}</em></summary><div class="section-actions"><button class="subtle" data-copy-section="${x.id}">Copy text</button><button class="subtle" data-copy-citation="${x.id}">Copy source label</button></div><pre>${esc(x.text)}</pre></details>`).join(''):'<div class="empty">No sections match this filter.</div>';$$('[data-copy-section]').forEach(b=>b.onclick=()=>navigator.clipboard.writeText(ss.find(x=>x.id===b.dataset.copySection)?.text||''));$$('[data-copy-citation]').forEach(b=>b.onclick=()=>{const x=ss.find(x=>x.id===b.dataset.copyCitation);navigator.clipboard.writeText(`${selected.name} — ${x?.heading||''} (${x?.location||''})`)})};
 $('#sectionFilter').oninput=drawSections;$('#sectionLevel').onchange=drawSections;$('#expandSections').onclick=()=>$$('#sectionResults details').forEach(x=>x.open=true);$('#collapseSections').onclick=()=>$$('#sectionResults details').forEach(x=>x.open=false);$('#exportExtraction').onclick=()=>download(`${selected.title.replace(/[^a-z0-9]+/gi,'-')}-extraction-report.json`,JSON.stringify({...report,sections:ss.map(({id,projectId,libraryId,documentId,...x})=>x)},null,2),'application/json');drawSections();
}
function renderEvals(){const es=state().evaluations;$('#evalList').innerHTML=es.length?es.map(e=>`<article class="eval"><div><strong>${esc(e.question)}</strong><span>Expected source: ${esc(e.expectedSource||'Any supporting source')}</span></div><button data-run="${e.id}">Run</button><button class="danger" data-del-eval="${e.id}">×</button></article>`).join(''):'<div class="empty">No evaluation cases yet.</div>';$$('[data-del-eval]').forEach(b=>b.onclick=()=>{engine.removeEvaluation(b.dataset.delEval);renderEvals()});$$('[data-run]').forEach(b=>b.onclick=async()=>{const e=state().evaluations.find(x=>x.id===b.dataset.run);b.disabled=true;b.textContent='Running…';try{const r=await engine.runEvaluation(e);$('#evalResult').innerHTML=`<div class="score ${r.score>=80?'good':r.score>=60?'warn':'bad'}">${r.score}<small>/100</small></div><h3>Result</h3><p>${r.citations} citation(s) · source match ${r.sourceMatch?'yes':'no'}</p><h4>Missing facts</h4><p>${r.missingFacts.map(esc).join('<br>')||'None'}</p><h4>Prohibited statements found</h4><p>${r.prohibitedHits.map(esc).join('<br>')||'None'}</p><details><summary>Answer</summary><pre>${esc(r.answer)}</pre></details>`}catch(err){alert(err.message)}finally{b.disabled=false;b.textContent='Run'}})}
$('#addEval').onclick=()=>openModal(`<h2>Add SME evaluation</h2><label>Question<textarea id="eQuestion"></textarea></label><label>Expected source or section<input id="eSource"></label><label>Required facts — one per line<textarea id="eFacts"></textarea></label><label>Prohibited assumptions — one per line<textarea id="eProhibited"></textarea></label><button id="saveEval">Save case</button>`,()=>{$('#saveEval').onclick=()=>{const q=$('#eQuestion').value.trim();if(!q)return;engine.addEvaluation({question:q,expectedSource:$('#eSource').value.trim(),requiredFacts:$('#eFacts').value.trim(),prohibited:$('#eProhibited').value.trim()});closeModal();renderEvals()}});
function loadSettings(){const s=state().settings;$('#apiUrl').value=s.openaiUrl;$('#model').value=s.openaiModel;$('#apiKey').value=s.openaiKey;$('#timeout').value=s.timeout/1000;$('#topK').value=s.topK}
$('#saveSettings').onclick=()=>{engine.saveSettings({openaiUrl:$('#apiUrl').value.trim(),openaiModel:$('#model').value.trim(),openaiKey:$('#apiKey').value.trim(),timeout:Number($('#timeout').value)*1000,topK:Number($('#topK').value)});alert('Settings saved in this browser.');refresh()};
$('#exportProject').onclick=async()=>{const data=await engine.exportProject();download(`${data.manifest.project.name.replace(/[^a-z0-9]+/gi,'-')}-mission-companion.json`,JSON.stringify(data,null,2),'application/json')};
$('#importProject').onchange=async()=>{try{await engine.importProject(JSON.parse(await $('#importProject').files[0].text()));await refresh();alert('Project imported.')}catch(e){alert(e.message)}};
function download(name,data,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function openModal(html,ready){$('#modalBody').innerHTML=html;$('#modal').hidden=false;ready?.()}function closeModal(){$('#modal').hidden=true}$('#closeModal').onclick=closeModal;$('#modal').onclick=e=>{if(e.target===$('#modal'))closeModal()};

$$('[data-settings-tab]').forEach(button=>{button.onclick=()=>{$$('[data-settings-tab]').forEach(x=>x.classList.toggle('active',x===button));$$('[data-settings-pane]').forEach(x=>x.classList.toggle('active',x.dataset.settingsPane===button.dataset.settingsTab))};button.dataset.bound='true'});
$('#testConnection').onclick=async()=>{const b=$('#testConnection');b.disabled=true;b.textContent='Testing…';try{engine.saveSettings({openaiUrl:$('#apiUrl').value.trim(),openaiModel:$('#model').value.trim(),openaiKey:$('#apiKey').value.trim()});await engine.testConnection();alert('OpenAI connection succeeded.');registerModule('AI Engine','ready',{summary:'Connection test passed'})}catch(e){captureError(e,{module:'AI Engine',action:'connection-test'});alert(e.message)}finally{b.disabled=false;b.textContent='Test connection'}};
$('#openDiagnostics').onclick=()=>show('diagnostics');
$('#resetApplication').onclick=async()=>{if(!confirm('This permanently removes all Mission Companion projects, documents, settings, and history stored in this browser. Continue?'))return;await engine.resetApplication();location.reload()};
$('#runDiagnostics').onclick=()=>renderDiagnostics();
$('#clearLogs').onclick=()=>{logger.clear();renderDiagnostics()};
$('#exportDiagnostics').onclick=()=>download(`mission-companion-diagnostics-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(diagnosticSnapshot(),null,2),'application/json');
window.addEventListener('mc:open-diagnostics',()=>show('diagnostics'));
window.addEventListener('mc:diagnostics',()=>{if(view==='diagnostics')renderDiagnosticLog()});
async function renderDiagnostics(){
  const data=await runHealthChecks(engine);
  const healthy=data.checks.filter(x=>x.status==='healthy'||x.status==='configured').length;
  const failures=data.checks.filter(x=>x.status==='failed').length;
  $('#healthSummary').innerHTML=`<article><span>STATUS</span><strong class="${failures?'bad-text':'good-text'}">${failures?'Attention required':'Operational'}</strong></article><article><span>CHECKS PASSED</span><strong>${healthy}/${data.checks.length}</strong></article><article><span>LIFECYCLE</span><strong>${esc(data.lifecycle)}</strong></article><article><span>VERSION</span><strong>2.4.0</strong></article>`;
  $('#healthChecks').innerHTML=data.checks.map(x=>`<article class="health-row ${x.status}"><span class="health-icon">${x.status==='healthy'||x.status==='configured'?'✓':x.status==='failed'?'×':'!'}</span><div><strong>${esc(x.name)}</strong><small>${esc(x.detail)}</small></div></article>`).join('');
  renderDiagnosticLog();
}
function renderDiagnosticLog(){const rows=logger.list().slice().reverse();$('#diagnosticLog').innerHTML=rows.length?rows.map(x=>`<article class="log-row ${x.level}"><time>${new Date(x.time).toLocaleTimeString()}</time><strong>${esc(x.level.toUpperCase())}</strong><span>${esc(x.message)}</span>${Object.keys(x.details||{}).length?`<details><summary>Details</summary><pre>${esc(JSON.stringify(x.details,null,2))}</pre></details>`:''}</article>`).join(''):'<div class="empty">No diagnostic events recorded.</div>'}
function verifyStartup(){
  const result=verifyButtons(['[data-view="chat"]','[data-view="knowledge"]','[data-view="sources"]','[data-view="evaluate"]','[data-view="settings"]','[data-view="diagnostics"]','#send','#upload','#saveSettings','#runDiagnostics']);
  registerModule('Button Verification',result.missing.length||result.unattached.length?'warning':'ready',{summary:`${result.attached}/${result.total} attached`,...result});
  registerModule('UI','ready',{summary:'Application shell rendered'});
  registerModule('Storage','ready',{summary:'Browser storage initialized'});
  $('#healthText').textContent=result.missing.length?'Startup warning':'System ready';
  $('#healthDot').classList.toggle('warning',!!result.missing.length);
}
loadSettings();
refresh().then(()=>{verifyStartup();setLifecycle('ready',{startupMs:Date.now()-(window.__MC_BOOT_TIME__||Date.now())});logger.info('Mission Companion ready',{version:'2.4.0'});}).catch(e=>{setLifecycle('error');captureError(e,{module:'Startup'})});

