import { engine } from './engine.js';
import { logger, setLifecycle, registerModule, captureError, verifyButtons, runHealthChecks, diagnosticSnapshot, installGlobalHandlers } from './diagnostics.js';
installGlobalHandlers();
setLifecycle('loading-ui');
const app=document.querySelector('#app');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>new Intl.NumberFormat().format(n||0);
let view='chat', selectedDoc=null, busy=false;

app.innerHTML=`
<div class="shell">
 <aside class="rail">
  <div class="brand"><div class="mark">M</div><div><strong>Mission Companion</strong><span>SME Workspace · Master 2.0</span></div></div>
  <nav>
   <button data-view="chat" class="active">Command Desk</button>
   <button data-view="knowledge">Knowledge Base</button>
   <button data-view="sources">Source Inspector</button>
   <button data-view="evaluate">SME Evaluations</button>
   <button data-view="settings">Settings</button>
   <button data-view="diagnostics">Diagnostics</button>
  </nav>
  <div class="project-block"><label>ACTIVE PROJECT</label><select id="projectSelect"></select><button id="newProject" class="subtle">＋ New project</button></div>
  <div class="rail-foot"><span class="dot" id="healthDot"></span><span id="healthText">Starting…</span></div>
 </aside>
 <main>
  <header class="topbar"><div><div class="eyebrow">MISSION COMPANION</div><h1 id="pageTitle">Command Desk</h1><p id="pageSub">Ask project-specific questions and receive source-grounded answers.</p></div><div class="mode-wrap"><label>ANSWER MODE</label><select id="mode"><option value="source">Source-only</option><option value="assisted">SME-assisted</option><option value="general">General assistant</option></select></div></header>
  <section id="chat" class="view active">
   <div class="kpis"><article><span>DOCUMENTS</span><strong id="kDocs">0</strong></article><article><span>INDEXED SECTIONS</span><strong id="kSections">0</strong></article><article><span>ANSWER STANDARD</span><strong id="kMode">Source-only</strong></article><article><span>AI</span><strong id="kAI">Not configured</strong></article></div>
   <div class="chat-layout">
    <section class="panel conversation"><div class="panel-head"><div><span>PROJECT ANALYSIS</span><h2>Ask Mission Companion</h2></div><button id="clearChat" class="subtle">New conversation</button></div><div id="messages" class="messages"></div><div class="composer"><textarea id="prompt" placeholder="Ask a question about the selected project knowledge…"></textarea><button id="send">Analyze</button></div><div class="hint">Enter sends · Shift+Enter adds a line</div></section>
    <aside class="panel evidence"><div class="panel-head"><div><span>RETRIEVAL</span><h2>Evidence used</h2></div></div><div id="evidenceList" class="evidence-list"><div class="empty">Sources used in the latest answer appear here.</div></div></aside>
   </div>
  </section>
  <section id="knowledge" class="view"><div class="split"><section class="panel"><div class="panel-head"><div><span>INGESTION PIPELINE</span><h2>Knowledge library</h2></div><div><input id="fileInput" type="file" multiple hidden accept=".pdf,.docx,.xlsx,.xls,.txt,.md,.csv,.json,.html,.xml,.log"><button id="upload">＋ Add documents</button></div></div><div class="pipeline"><span>Upload</span><b>→</b><span>Extract</span><b>→</b><span>Detect sections</span><b>→</b><span>Index</span><b>→</b><span>Verify</span></div><div id="ingestStatus"></div><div id="documents" class="document-list"></div></section><aside class="panel guide"><h3>Supported knowledge</h3><p>PDF, Word, Excel, text, Markdown, CSV, JSON, HTML, XML, and logs.</p><h3>Indexing behavior</h3><p>Mission Companion preserves document names, headings, section order, and PDF page markers. Long sections are divided without losing their parent heading.</p><h3>Accuracy rule</h3><p>Source-only mode refuses to fill gaps with general knowledge.</p></aside></div></section>
  <section id="sources" class="view"><div class="split source-split"><section class="panel"><div class="panel-head"><div><span>DOCUMENT STRUCTURE</span><h2>Source inspector</h2></div></div><div id="sourceDocs" class="source-docs"></div></section><section class="panel"><div id="sourceDetail" class="source-detail"><div class="empty">Choose a document to inspect its indexed sections.</div></div></section></div></section>
  <section id="evaluate" class="view"><div class="split"><section class="panel"><div class="panel-head"><div><span>ACCURACY BENCHMARK</span><h2>SME evaluation cases</h2></div><button id="addEval">＋ Add case</button></div><p class="intro">Create known-answer questions. Each run scores required facts, prohibited assumptions, source retrieval, and citation use.</p><div id="evalList"></div></section><aside class="panel"><h3>Evaluation standard</h3><p><strong>Required facts</strong> are phrases the answer must contain.</p><p><strong>Expected source</strong> is a document or section the retrieval should find.</p><p><strong>Prohibited assumptions</strong> are statements that must not appear.</p><div id="evalResult"></div></aside></div></section>
  <section id="settings" class="view"><section class="panel settings"><div class="panel-head"><div><span>APPLICATION SETTINGS</span><h2>Settings</h2></div></div><div class="settings-tabs"><button class="active" data-settings-tab="ai">AI</button><button data-settings-tab="knowledge">Knowledge</button><button data-settings-tab="developer">Developer</button><button data-settings-tab="about">About</button></div><div class="settings-pane active" data-settings-pane="ai"><label>OpenAI API URL<input id="apiUrl"></label><label>Model<input id="model"></label><label>API key<input id="apiKey" type="password" autocomplete="off"></label><label>Request timeout (seconds)<input id="timeout" type="number" min="30" max="600"></label><button id="testConnection" class="subtle">Test connection</button></div><div class="settings-pane" data-settings-pane="knowledge"><label>Retrieved sections per question<input id="topK" type="number" min="3" max="20"></label><div class="settings-actions"><button id="exportProject" class="subtle">Export project</button><label class="button subtle">Import project<input id="importProject" type="file" accept=".json" hidden></label></div></div><div class="settings-pane" data-settings-pane="developer"><p class="notice">Reset removes all projects, settings, indexed documents, and browser history for this application.</p><button id="openDiagnostics" class="subtle">Open diagnostics</button><button id="resetApplication" class="danger">Reset application data</button></div><div class="settings-pane" data-settings-pane="about"><h3>Mission Companion Master</h3><p>Version <strong>2.1.0 — Build 1</strong></p><p class="notice">Evidence-first SME workspace. Build 1 adds lifecycle management, diagnostics, health checks, recovery, structured logging, and startup verification.</p></div><div class="settings-actions"><button id="saveSettings">Save settings</button></div><p class="notice">The API key is stored only in this browser. A public static website cannot safely share one central key.</p></section></section>
  <section id="diagnostics" class="view"><div class="diagnostic-grid"><section class="panel"><div class="panel-head"><div><span>SYSTEM HEALTH</span><h2>Diagnostics</h2></div><div><button id="runDiagnostics">Run checks</button><button id="exportDiagnostics" class="subtle">Export</button></div></div><div id="healthSummary" class="health-summary"></div><div id="healthChecks" class="health-checks"></div></section><section class="panel"><div class="panel-head"><div><span>DEVELOPER CONSOLE</span><h2>Application log</h2></div><button id="clearLogs" class="subtle">Clear log</button></div><div id="diagnosticLog" class="diagnostic-log"></div></section><section class="panel roadmap-panel"><div class="panel-head"><div><span>MASTER ROADMAP</span><h2>Build sequence</h2></div></div><ol class="roadmap"><li class="done"><strong>Build 1</strong><span>Stabilization and diagnostics</span></li><li><strong>Build 2</strong><span>Document ingestion and section hierarchy</span></li><li><strong>Build 3</strong><span>Source Inspector and extraction verification</span></li><li><strong>Build 4</strong><span>Retrieval and reranking</span></li><li><strong>Build 5</strong><span>Evidence-controlled answer engine</span></li><li><strong>Build 6</strong><span>Citation accuracy</span></li><li><strong>Build 7</strong><span>SME evaluation suite</span></li><li><strong>Build 8–10</strong><span>Knowledge packs, security, and production release</span></li></ol></section></div></section>
 </main>
</div>
<div id="modal" class="modal" hidden><div class="modal-card"><button id="closeModal" class="modal-x">×</button><div id="modalBody"></div></div></div>`;

const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const titles={diagnostics:['Diagnostics','Inspect application health, startup checks, logs, and roadmap.'],chat:['Command Desk','Ask project-specific questions and receive source-grounded answers.'],knowledge:['Knowledge Base','Build a structured, section-aware project library.'],sources:['Source Inspector','Review exactly what Mission Companion indexed.'],evaluate:['SME Evaluations','Measure accuracy against known questions and required evidence.'],settings:['Settings','Configure the model and move project libraries between browsers.']};
function show(name){view=name;$$('.view').forEach(x=>x.classList.toggle('active',x.id===name));$$('nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===name));$('#pageTitle').textContent=titles[name][0];$('#pageSub').textContent=titles[name][1];if(name==='sources')renderSources();if(name==='evaluate')renderEvals();if(name==='diagnostics')renderDiagnostics()}
$$('nav button').forEach(b=>{b.onclick=()=>show(b.dataset.view);b.dataset.bound='true'});registerModule('Navigation','ready',{summary:`${$$('nav button').length} views registered`});
function state(){return engine.state()}
function modeLabel(m){return {source:'Source-only',assisted:'SME-assisted',general:'General assistant'}[m]}
async function refresh(){const s=state();$('#mode').value=s.settings.mode;$('#kMode').textContent=modeLabel(s.settings.mode);$('#kAI').textContent=s.settings.openaiKey?'Configured':'Not configured';$('#projectSelect').innerHTML=s.projects.map(p=>`<option value="${p.id}" ${p.id===s.activeProject?'selected':''}>${esc(p.name)}</option>`).join('');const docs=await engine.documents(),sections=await engine.sections();$('#kDocs').textContent=fmt(docs.length);$('#kSections').textContent=fmt(sections.length);renderMessages();renderDocuments(docs)}
$('#mode').onchange=()=>{engine.saveSettings({mode:$('#mode').value});refresh()};
$('#projectSelect').onchange=async()=>{engine.setProject($('#projectSelect').value);selectedDoc=null;await refresh()};
$('#newProject').onclick=()=>openModal(`<h2>Create project</h2><label>Project name<input id="projectName" autofocus></label><button id="createProject">Create</button>`,()=>{$('#createProject').onclick=()=>{const n=$('#projectName').value.trim();if(n){engine.addProject(n);closeModal();refresh()}}});
function renderMessages(){const chat=state().chat;$('#messages').innerHTML=chat.length?chat.map(m=>`<article class="message ${m.role}"><div class="avatar">${m.role==='user'?'YOU':'MC'}</div><div><div class="message-meta">${m.role==='user'?'You':'Mission Companion'}${m.mode?` · ${modeLabel(m.mode)}`:''}</div><div class="message-text">${esc(m.content).replace(/\n/g,'<br>')}</div></div></article>`).join(''):`<div class="welcome"><div class="seal">M</div><h3>Build an evidence-backed SME</h3><p>Add project documents, choose Source-only mode, and ask questions. Mission Companion will retrieve the most relevant sections, cite them, and identify evidence gaps.</p></div>`;$('#messages').scrollTop=$('#messages').scrollHeight}
$('#clearChat').onclick=()=>{engine.clearChat();refresh()};
async function ask(){const prompt=$('#prompt').value.trim();if(!prompt||busy)return;busy=true;$('#send').disabled=true;$('#send').textContent='Analyzing…';try{const m=await engine.ask(prompt,$('#mode').value);$('#prompt').value='';renderMessages();renderEvidence(m.hits,m.citations)}catch(e){captureError(e,{module:'Conversation',action:'ask'});alert(e.message)}finally{busy=false;$('#send').disabled=false;$('#send').textContent='Analyze'}}
$('#send').onclick=ask;$('#prompt').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();ask()}};
function renderEvidence(hits=[],used=[]){$('#evidenceList').innerHTML=hits.length?hits.map(h=>`<article class="evidence-item ${used.includes(h.sourceNumber)?'used':''}"><div><strong>[S${h.sourceNumber}] ${esc(h.heading)}</strong><span>${esc(h.documentName)} · ${esc(h.location)} · score ${h.score.toFixed(1)}</span></div><p>${esc(h.text.slice(0,320))}${h.text.length>320?'…':''}</p></article>`).join(''):'<div class="empty">No project evidence was retrieved.</div>'}
$('#upload').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=async()=>{const files=[...$('#fileInput').files];if(!files.length)return;$('#ingestStatus').innerHTML='<div class="progress">Preparing files…</div>';const r=await engine.ingest(files,p=>{$('#ingestStatus').innerHTML=`<div class="progress">Processing ${esc(p.name)} (${p.current}/${p.total})…</div>`});$('#ingestStatus').innerHTML=`<div class="success">Indexed ${r.sections.length} sections from ${r.documents.filter(d=>d.status==='verified').length} document(s).</div>`;$('#fileInput').value='';refresh()};
function renderDocuments(docs){$('#documents').innerHTML=docs.length?docs.map(d=>`<article class="doc ${d.status}"><div class="file-icon">${(d.name.split('.').pop()||'DOC').toUpperCase().slice(0,4)}</div><div class="doc-main"><strong>${esc(d.name)}</strong><span>${d.status==='error'?esc(d.error):`${fmt(d.sectionCount)} sections · ${fmt(d.characterCount)} characters · ${new Date(d.indexedAt).toLocaleString()}`}</span></div><button class="subtle" data-inspect="${d.id}">Inspect</button><button class="danger" data-remove="${d.id}">Remove</button></article>`).join(''):'<div class="empty">No documents have been added to this project.</div>';$$('[data-remove]').forEach(b=>b.onclick=async()=>{if(confirm('Remove this document and all indexed sections?')){await engine.removeDocument(b.dataset.remove);refresh()}});$$('[data-inspect]').forEach(b=>b.onclick=()=>{selectedDoc=b.dataset.inspect;show('sources')})}
async function renderSources(){const docs=await engine.documents(),sections=await engine.sections();$('#sourceDocs').innerHTML=docs.length?docs.map(d=>`<button class="source-doc ${d.id===selectedDoc?'active':''}" data-doc="${d.id}"><strong>${esc(d.name)}</strong><span>${d.sectionCount} sections</span></button>`).join(''):'<div class="empty">No indexed documents.</div>';$$('[data-doc]').forEach(b=>b.onclick=()=>{selectedDoc=b.dataset.doc;renderSources()});const selected=docs.find(d=>d.id===selectedDoc)||docs[0];if(selected){selectedDoc=selected.id;const ss=sections.filter(s=>s.documentId===selected.id).sort((a,b)=>a.order-b.order);$('#sourceDetail').innerHTML=`<div class="source-title"><span>INDEXED DOCUMENT</span><h2>${esc(selected.name)}</h2><p>${ss.length} sections · ${fmt(selected.characterCount)} characters</p></div>${ss.map((s,i)=>`<details ${i===0?'open':''}><summary><b>${i+1}</b><span>${esc(s.heading)}</span><small>${esc(s.location)} · ${fmt(s.characters)} chars</small></summary><pre>${esc(s.text)}</pre></details>`).join('')}`}}
function renderEvals(){const es=state().evaluations;$('#evalList').innerHTML=es.length?es.map(e=>`<article class="eval"><div><strong>${esc(e.question)}</strong><span>Expected source: ${esc(e.expectedSource||'Any supporting source')}</span></div><button data-run="${e.id}">Run</button><button class="danger" data-del-eval="${e.id}">×</button></article>`).join(''):'<div class="empty">No evaluation cases yet.</div>';$$('[data-del-eval]').forEach(b=>b.onclick=()=>{engine.removeEvaluation(b.dataset.delEval);renderEvals()});$$('[data-run]').forEach(b=>b.onclick=async()=>{const e=state().evaluations.find(x=>x.id===b.dataset.run);b.disabled=true;b.textContent='Running…';try{const r=await engine.runEvaluation(e);$('#evalResult').innerHTML=`<div class="score ${r.score>=80?'good':r.score>=60?'warn':'bad'}">${r.score}<small>/100</small></div><h3>Result</h3><p>${r.citations} citation(s) · source match ${r.sourceMatch?'yes':'no'}</p><h4>Missing facts</h4><p>${r.missingFacts.map(esc).join('<br>')||'None'}</p><h4>Prohibited statements found</h4><p>${r.prohibitedHits.map(esc).join('<br>')||'None'}</p><details><summary>Answer</summary><pre>${esc(r.answer)}</pre></details>`}catch(err){alert(err.message)}finally{b.disabled=false;b.textContent='Run'}})}
$('#addEval').onclick=()=>openModal(`<h2>Add SME evaluation</h2><label>Question<textarea id="eQuestion"></textarea></label><label>Expected source or section<input id="eSource"></label><label>Required facts — one per line<textarea id="eFacts"></textarea></label><label>Prohibited assumptions — one per line<textarea id="eProhibited"></textarea></label><button id="saveEval">Save case</button>`,()=>{$('#saveEval').onclick=()=>{const q=$('#eQuestion').value.trim();if(!q)return;engine.addEvaluation({question:q,expectedSource:$('#eSource').value.trim(),requiredFacts:$('#eFacts').value.trim(),prohibited:$('#eProhibited').value.trim()});closeModal();renderEvals()}});
function loadSettings(){const s=state().settings;$('#apiUrl').value=s.openaiUrl;$('#model').value=s.openaiModel;$('#apiKey').value=s.openaiKey;$('#timeout').value=s.timeout/1000;$('#topK').value=s.topK}
$('#saveSettings').onclick=()=>{engine.saveSettings({openaiUrl:$('#apiUrl').value.trim(),openaiModel:$('#model').value.trim(),openaiKey:$('#apiKey').value.trim(),timeout:Number($('#timeout').value)*1000,topK:Number($('#topK').value)});alert('Settings saved in this browser.');refresh()};
$('#exportProject').onclick=async()=>{const data=await engine.exportProject();download(`${data.manifest.project.name.replace(/[^a-z0-9]+/gi,'-')}-mission-companion.json`,JSON.stringify(data,null,2),'application/json')};
$('#importProject').onchange=async()=>{try{await engine.importProject(JSON.parse(await $('#importProject').files[0].text()));await refresh();alert('Project imported.')}catch(e){alert(e.message)}};
function download(name,data,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function openModal(html,ready){$('#modalBody').innerHTML=html;$('#modal').hidden=false;ready?.()}function closeModal(){$('#modal').hidden=true}$('#closeModal').onclick=closeModal;$('#modal').onclick=e=>{if(e.target===$('#modal'))closeModal()};

$$('[data-settings-tab]').forEach(button=>{button.onclick=()=>{$$('[data-settings-tab]').forEach(x=>x.classList.toggle('active',x===button));$$('[data-settings-pane]').forEach(x=>x.classList.toggle('active',x.dataset.settingsPane===button.dataset.settingsTab))};button.dataset.bound='true'});
$('#testConnection').onclick=async()=>{const b=$('#testConnection');b.disabled=true;b.textContent='Testing…';try{engine.saveSettings({openaiUrl:$('#apiUrl').value.trim(),openaiModel:$('#model').value.trim(),openaiKey:$('#apiKey').value.trim()});await engine.testConnection();alert('OpenAI connection succeeded.');registerModule('AI Engine','ready',{summary:'Connection test passed'})}catch(e){captureError(e,{module:'AI Engine',action:'connection-test'});alert(e.message)}finally{b.disabled=false;b.textContent='Test connection'}};
$('#openDiagnostics').onclick=()=>show('diagnostics');
$('#resetApplication').onclick=async()=>{if(!confirm('This permanently removes all Mission Companion projects, documents, settings, and history stored in this browser. Continue?'))return;await engine.resetApplication();location.reload()};
$('#runDiagnostics').onclick=()=>renderDiagnostics();
$('#clearLogs').onclick=()=>{logger.clear();renderDiagnostics()};
$('#exportDiagnostics').onclick=()=>download(`mission-companion-diagnostics-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(diagnosticSnapshot(),null,2),'application/json');
window.addEventListener('mc:open-diagnostics',()=>show('diagnostics'));
window.addEventListener('mc:diagnostics',()=>{if(view==='diagnostics')renderDiagnosticLog()});
async function renderDiagnostics(){
  const data=await runHealthChecks(engine);
  const healthy=data.checks.filter(x=>x.status==='healthy'||x.status==='configured').length;
  const failures=data.checks.filter(x=>x.status==='failed').length;
  $('#healthSummary').innerHTML=`<article><span>STATUS</span><strong class="${failures?'bad-text':'good-text'}">${failures?'Attention required':'Operational'}</strong></article><article><span>CHECKS PASSED</span><strong>${healthy}/${data.checks.length}</strong></article><article><span>LIFECYCLE</span><strong>${esc(data.lifecycle)}</strong></article><article><span>VERSION</span><strong>2.1.0</strong></article>`;
  $('#healthChecks').innerHTML=data.checks.map(x=>`<article class="health-row ${x.status}"><span class="health-icon">${x.status==='healthy'||x.status==='configured'?'✓':x.status==='failed'?'×':'!'}</span><div><strong>${esc(x.name)}</strong><small>${esc(x.detail)}</small></div></article>`).join('');
  renderDiagnosticLog();
}
function renderDiagnosticLog(){const rows=logger.list().slice().reverse();$('#diagnosticLog').innerHTML=rows.length?rows.map(x=>`<article class="log-row ${x.level}"><time>${new Date(x.time).toLocaleTimeString()}</time><strong>${esc(x.level.toUpperCase())}</strong><span>${esc(x.message)}</span>${Object.keys(x.details||{}).length?`<details><summary>Details</summary><pre>${esc(JSON.stringify(x.details,null,2))}</pre></details>`:''}</article>`).join(''):'<div class="empty">No diagnostic events recorded.</div>'}
function verifyStartup(){
  const result=verifyButtons(['[data-view="chat"]','[data-view="knowledge"]','[data-view="sources"]','[data-view="evaluate"]','[data-view="settings"]','[data-view="diagnostics"]','#send','#upload','#saveSettings','#runDiagnostics']);
  registerModule('Button Verification',result.missing.length||result.unattached.length?'warning':'ready',{summary:`${result.attached}/${result.total} attached`,...result});
  registerModule('UI','ready',{summary:'Application shell rendered'});
  registerModule('Storage','ready',{summary:'Browser storage initialized'});
  $('#healthText').textContent=result.missing.length?'Startup warning':'System ready';
  $('#healthDot').classList.toggle('warning',!!result.missing.length);
}
loadSettings();
refresh().then(()=>{verifyStartup();setLifecycle('ready',{startupMs:Date.now()-(window.__MC_BOOT_TIME__||Date.now())});logger.info('Mission Companion ready',{version:'2.1.0'});}).catch(e=>{setLifecycle('error');captureError(e,{module:'Startup'})});

