function uid(){return crypto.randomUUID()}
function clean(s){return String(s||'').replace(/\r/g,'').replace(/[ \t]+\n/g,'\n').replace(/\n{4,}/g,'\n\n\n').trim()}
function splitSections(text,name){const lines=clean(text).split('\n');const out=[];let heading='Document beginning',buf=[],start=1;const push=(end)=>{const t=clean(buf.join('\n'));if(t)out.push({heading,text:t,location:`Lines ${start}-${end}`});buf=[]};lines.forEach((line,i)=>{const h=line.trim();const isHeading=/^(#{1,6}\s+|(?:SECTION|CHAPTER|PART|ARTICLE|APPENDIX)\s+[A-Z0-9]|\d+(?:\.\d+){0,4}\s+[A-Z]|[A-Z][A-Z0-9 /&(),'-]{5,80})$/.test(h)&&h.length<140;if(isHeading&&buf.join(' ').length>250){push(i);heading=h.replace(/^#+\s*/,'');start=i+1}else buf.push(line)});push(lines.length);return out.flatMap(s=>s.text.length>7000?chunkLong(s):[s])}
function chunkLong(s){const paras=s.text.split(/\n\s*\n/);const out=[];let buf='';let n=1;for(const p of paras){if((buf+'\n\n'+p).length>6500&&buf){out.push({...s,heading:`${s.heading} — Part ${n++}`,text:buf});buf=p}else buf+=(buf?'\n\n':'')+p}if(buf)out.push({...s,heading:n>1?`${s.heading} — Part ${n}`:s.heading,text:buf});return out}
async function loadScript(src,test){if(test())return;await new Promise((res,rej)=>{const s=document.createElement('script');s.src=src;s.onload=res;s.onerror=()=>rej(new Error(`Could not load parser: ${src}`));document.head.appendChild(s)})}
async function parsePDF(file){const pdfjs=await import('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs');pdfjs.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs';const pdf=await pdfjs.getDocument({data:await file.arrayBuffer()}).promise;const pages=[];for(let i=1;i<=pdf.numPages;i++){const page=await pdf.getPage(i);const c=await page.getTextContent();pages.push(`PAGE ${i}\n${c.items.map(x=>x.str).join(' ')}`)}return pages.join('\n\n')}
async function parseDocx(file){await loadScript('https://cdn.jsdelivr.net/npm/mammoth@1.8.0/mammoth.browser.min.js',()=>window.mammoth);const r=await window.mammoth.extractRawText({arrayBuffer:await file.arrayBuffer()});return r.value}
async function parseXlsx(file){await loadScript('https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js',()=>window.XLSX);const wb=window.XLSX.read(await file.arrayBuffer(),{type:'array'});return wb.SheetNames.map(n=>`SHEET: ${n}\n${window.XLSX.utils.sheet_to_csv(wb.Sheets[n])}`).join('\n\n')}
async function parseFile(file){const ext=file.name.split('.').pop().toLowerCase();if(['txt','md','csv','json','html','htm','xml','log'].includes(ext))return file.text();if(ext==='docx')return parseDocx(file);if(['xlsx','xls'].includes(ext))return parseXlsx(file);if(ext==='pdf')return parsePDF(file);throw new Error(`Unsupported file type: .${ext}`)}
export async function parseFiles(files,projectId,onProgress=()=>{}){const documents=[],sections=[];let i=0;for(const file of files){onProgress({current:++i,total:files.length,name:file.name});try{const text=clean(await parseFile(file));const documentId=uid();const parts=splitSections(text,file.name);documents.push({id:documentId,projectId,name:file.name,type:file.type||file.name.split('.').pop(),size:file.size,sectionCount:parts.length,characterCount:text.length,indexedAt:new Date().toISOString(),status:'verified'});parts.forEach((p,n)=>sections.push({id:uid(),projectId,documentId,documentName:file.name,heading:p.heading,location:p.location,order:n,text:p.text,characters:p.text.length}))}catch(error){documents.push({id:uid(),projectId,name:file.name,type:file.type,size:file.size,sectionCount:0,characterCount:0,indexedAt:new Date().toISOString(),status:'error',error:error.message})}}return {documents,sections}}
